[project]
name = 'Work-Life-Balance-Imbalancer'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.leisure-kpi-dashboard]
path = 'contracts/leisure-kpi-dashboard.clar'
clarity_version = 3
epoch = '3.2'

[contracts.mindfulness-notification-storm]
path = 'contracts/mindfulness-notification-storm.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
